name: commitlint

on:
  repository_dispatch:
    types: [commitlint]

jobs:
  commitlint:
#    if: ${{ github.event.client_payload.pull_request && github.event.client_payload.pull_request.base.ref == github.event.client_payload.pull_request.base.repo.default_branch }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Pulls all commits (needed for semantic release to correctly version)
          # See https://github.com/semantic-release/semantic-release/issues/1526
          fetch-depth: 0
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}

      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Github Identity
        run: |
          git config --global user.name "goparrot-bot"
          git config --global user.email "bot@goparrot.ai"
          git remote set-url origin https://x-access-token:${{ secrets.GH_RELEASE_TOKEN }}@github.com/${{ github.event.client_payload.github.payload.repository.full_name }}


      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v2
        env:
          GITHUB_SHA: ${{ github.event.client_payload.pull_request.head.sha }}
          GITHUB_REF: ${{ github.event.client_payload.pull_request.base.sha }}
          GITHUB_HEAD_REF: ${{ github.event.client_payload.pull_request.head.ref }}
          GITHUB_BASE_REF: ${{ github.event.client_payload.pull_request.base.ref }}

#      - name: Run linters
#        uses: wearerequired/lint-action@v1
#        with:
#          eslint: true
#          prettier: true

#      - name: Lints Pull Request commits
#        uses: wagoid/commitlint-github-action@v2
#        env:
#          GITHUB_SHA: ${{ github.event.client_payload.origin_github.sha }}
#          GITHUB_REF: ${{ github.event.client_payload.origin_github.event.ref }}
#          GITHUB_HEAD_REF: ${{ github.event.client_payload.origin_github.sha }}
#          GITHUB_BASE_REF: ${{ github.event.client_payload.origin_github.event.base_ref }}

        # ruscon/commitlint-github-action@hotfix/fatal-bad-error

#  wagoidcommitlintgithubaction203_f31bcd --label 179394 --workdir /github/workspace --rm -e INPUT_CONFIGFILE -e INPUT_FIRSTPARENT -e INPUT_FAILONWARNINGS -e INPUT_HELPURL -e INPUT_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/playground/playground":"/github/workspace" wagoid/commitlint-github-action:2.0.3
