name: commitlint

on:
  repository_dispatch:
    types: [org-workflow-bot]
#  push:
#    branches: [master, main]
#  pull_request:
#    branches: [master, main]

jobs:
  register:
#    if: ${{ github.event.client_payload.ref == 'refs/heads/master' || github.event.client_payload.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: SvanBoxel/organization-workflow@main
        with:
          id: ${{ github.event.client_payload.id }}
          callback_url: ${{ github.event.client_payload.callback_url }}
          sha: ${{ github.event.client_payload.sha }}
          run_id: ${{ github.run_id }}
          name: ${{ github.workflow }}
          enforce: true
          documentation: ".github/workflows/commitlint.md"

  commitlint:
    needs: [register]
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ toJson(github.event) }}"

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # Pulls all commits (needed for semantic release to correctly version)
          # See https://github.com/semantic-release/semantic-release/issues/1526
          fetch-depth: 0
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}
#          ref: ${{ github.head_ref }}
#          token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true

#      - name: Lints Pull Request commits
#        uses: wagoid/commitlint-github-action@v2
#        env:
#          GITHUB_SHA: ${{ github.event.client_payload.sha }}
#          GITHUB_REF: ${{ github.event.client_payload.event.ref }}
#          GITHUB_HEAD_REF: ${{ github.event.client_payload.sha }}
#          GITHUB_BASE_REF: ${{ github.event.client_payload.event.base_ref }}

        # ruscon/commitlint-github-action@hotfix/fatal-bad-error

#  wagoidcommitlintgithubaction203_f31bcd --label 179394 --workdir /github/workspace --rm -e INPUT_CONFIGFILE -e INPUT_FIRSTPARENT -e INPUT_FAILONWARNINGS -e INPUT_HELPURL -e INPUT_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/playground/playground":"/github/workspace" wagoid/commitlint-github-action:2.0.3
